import { formatUnits } from 'viem';
import { formatNumber } from '../../lib/formatting';
import { carveDestination, type EarnVerdict } from '../../lib/referrals/qualification';

// THE DISCLOSURE. This component exists for one sentence, and the sentence has
// to be on screen BEFORE anybody shares a link.
//
// ─── WHAT IT DISCLOSES ───────────────────────────────────────────────────────
//
// ReferralSplitter.recordFee credits a referrer only when their voting power
// clears MIN_REFERRAL_STAKE_POWER. Below it, the referrer's share is added to
// `accumulatedTreasuryETH` and `UnclaimableSentToTreasury` is emitted. Read the
// consequence carefully, because it is not "you earn less":
//
//   · the referee still pays the identical swap fee,
//   · the referrer's carve is still taken out of it,
//   · and it goes to the treasury instead of to the referrer.
//
// Nothing on-chain tells the referrer this happened. `getReferralInfo` returns
// the same three zeroes it returns for a wallet that has referred nobody, so the
// disqualified referrer and the referrer with no referees render identically —
// and only one of them is being told the truth. By the time someone opens a
// claim page and finds it empty, the fees are already in the treasury and
// nothing recovers them.
//
// So this is not a footnote under a Claim button. It is rendered above the share
// controls by ReferralsPanel, and referralsDisclosure.test.tsx pins both the
// text and that ordering.
//
// ─── WHY THE RULE IS ALSO STATED WITHOUT A WALLET ────────────────────────────
//
// The verdict needs a connected wallet; the RULE does not. A visitor reading
// this page disconnected — deciding whether the programme is worth joining — is
// exactly the person the threshold is most likely to surprise. So the standing
// paragraph is unconditional and the wallet-specific verdict is added to it,
// rather than the paragraph appearing only once a verdict exists.
//
// ─── AND WHY `unknown` IS LOUD ───────────────────────────────────────────────
//
// A failed read renders as its own amber state, never as green and never as a
// shortfall. Telling someone they qualify on the strength of a read that did not
// happen sends them off to recruit for the treasury; telling them they do not
// qualify because an RPC hiccuped makes them unstake for nothing. Both are worse
// than saying we could not check.

interface Props {
  earn: EarnVerdict;
  /** True while the first round of reads is in flight and no verdict exists. */
  isLoading: boolean;
  /** False means there is no wallet to have a verdict about. Not a failure. */
  connected: boolean;
  /** `referralFeeBps` as read from chain; null when that read failed. */
  referralFeeBps: number | null;
}

/** Voting power is 18-decimal; render it as a plain grouped number. */
function power(value: bigint): string {
  return formatNumber(Number(formatUnits(value, 18)), 0);
}

type Tone = 'good' | 'warn' | 'neutral';

const TONE_STYLE: Record<Tone, { background: string; border: string; color: string }> = {
  good: { background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.22)', color: '#7CFFB2' },
  warn: { background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.28)', color: '#FFD37C' },
  neutral: { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.12)', color: '#FFFFFF' },
};

interface Verdict {
  tone: Tone;
  headline: string;
  body: string;
}

function describe(earn: EarnVerdict, isLoading: boolean, connected: boolean): Verdict {
  if (!connected) {
    return {
      tone: 'neutral',
      headline: 'Connect a wallet to see whether yours qualifies',
      body:
        'The threshold above is the contract’s, not a policy of this page. Whether a particular wallet clears it is an on-chain read, and there is no wallet to read yet.',
    };
  }
  if (isLoading) {
    return {
      tone: 'neutral',
      headline: 'Checking your standing on-chain…',
      body: 'Reading your voting power and the splitter’s threshold. Nothing is claimed either way until both answer.',
    };
  }

  switch (earn.kind) {
    case 'qualified':
      return {
        tone: 'good',
        headline: `You qualify — ${power(earn.power)} of ${power(earn.threshold)} voting power`,
        body:
          'Fees generated by wallets that link you as their referrer credit your claimable balance. This is checked again at the moment each fee is recorded, so it is a statement about now, not a permanent status.',
      };
    case 'below-threshold':
      return {
        tone: 'warn',
        headline: `You do NOT qualify — ${power(earn.power)} of ${power(earn.threshold)} voting power`,
        body:
          `You are ${power(earn.shortfall)} short. If you share a link today, everyone who joins through it still pays the same swap fee and your share of it is still taken — it goes to the treasury instead of to you, and nothing you do later recovers the fees taken while you were below the line. Stake or lock to clear the threshold first.`,
      };
    case 'banned':
      return { tone: 'warn', headline: 'This address cannot earn referral fees', body: earn.reason };
    case 'engine-inert':
      return { tone: 'warn', headline: 'The referral splitter is not switched on', body: earn.reason };
    case 'unknown':
      return {
        tone: 'warn',
        headline: 'Your standing could not be checked',
        body: `${earn.reason} Treat this as unknown rather than as a pass: sharing a link on the strength of a read that did not happen is the same bet as sharing one while disqualified.`,
      };
  }
}

/** Where the carve lands, in one clause, for the standing paragraph. */
const DESTINATION_CLAUSE: Record<ReturnType<typeof carveDestination>, string> = {
  referrer: 'Right now, yours reaches you.',
  treasury: 'Right now, yours does not reach you — it reaches the treasury.',
  unknown: 'Whether yours reaches you could not be determined.',
};

export function ReferralQualificationNotice({ earn, isLoading, connected, referralFeeBps }: Props) {
  const verdict = describe(earn, isLoading, connected);
  const style = TONE_STYLE[verdict.tone];
  const showDestination = connected && !isLoading;

  return (
    <section
      className="rounded-xl p-4"
      style={{ background: '#000', border: '1px solid var(--color-purple-75)' }}
      aria-label="Referral earning requirement"
    >
      <h3 className="text-white text-[13px] font-medium">Before you share a link</h3>

      {/* UNCONDITIONAL. No wallet, no read, no verdict required — this is what the
          deployed contract does, and it is the half a prospective referrer most
          needs and is least likely to be told. */}
      <p className="mt-2 text-white/80 text-[12px] leading-relaxed">
        A referrer only earns while their own staking power clears the splitter’s threshold of{' '}
        <strong className="text-white">1,000 TOWELI</strong> (staked and restaked voting power count together). Below
        that line the referral share is still taken out of the referee’s swap fee — it is{' '}
        <strong className="text-white">paid to the treasury instead of to the referrer</strong>. Nothing on-chain tells
        the referrer it happened, and those fees are not recoverable later.
      </p>

      <p className="mt-2 text-white/60 text-[11px] leading-relaxed">
        {referralFeeBps === null ? (
          <>
            The size of that share is set on-chain and is changeable behind a timelock. This page could not read it just
            now, so no percentage is printed here rather than a stale one.
          </>
        ) : (
          <>
            The share is currently <strong className="text-white/80">{(referralFeeBps / 100).toFixed(2)}%</strong> of the
            referee’s swap fee, read from the contract just now. It is changeable behind a 24-hour timelock.
          </>
        )}{' '}
        The person who follows your link receives nothing extra — no discount, no bonus. The splitter pays the referrer
        only.
      </p>

      <div className="mt-3 rounded-lg p-3" style={style} role={verdict.tone === 'warn' ? 'alert' : undefined}>
        <p className="text-[12px] font-medium" style={{ color: style.color }}>
          {verdict.headline}
        </p>
        <p className="mt-1 text-white/70 text-[11px] leading-relaxed">{verdict.body}</p>
        {showDestination && (
          <p className="mt-1 text-white/50 text-[11px] leading-relaxed">{DESTINATION_CLAUSE[carveDestination(earn)]}</p>
        )}
      </div>
    </section>
  );
}

export default ReferralQualificationNotice;
