// @vitest-environment node
//
// NODE, not the project's jsdom default — the same choice `curve/ix.test.ts`
// makes for the same reason. Under jsdom, `PublicKey.findProgramAddressSync`
// fails every bump and throws "Unable to find a viable program address nonce",
// which names nothing about the environment and reads like a bad seed. This is a
// Node CLI; jsdom was never the right host for it.
//
// Pins for the bayla-ladder operator CLI.
//
// EVERY VALUE BELOW WAS VERIFIED AGAINST THE PROGRAM'S OWN IDL, generated by
// `anchor build` in the `solana-deploy-artifact` workflow (run 34303749601,
// commit 193a2064). Not derived from the source by eye, and not from memory:
// the IDL was downloaded and compared field by field, 0 mismatches.
//
// This file exists because none of these can fail LOCALLY. A wrong
// discriminator, a reordered account list or a shifted struct offset produces a
// confusing on-chain constraint failure against a deployed program — after a
// deploy has been paid for — rather than anything a type check or a dry run on
// an empty cluster would surface. Pinning them is the only way drift gets
// caught on this side of a transaction.
import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { PublicKey } from '@solana/web3.js';
import {
  IX, ACCT, POOL_L, POSITION_L, USER_L,
  poolPda, vaultPda, userPda, positionPda,
  decodePool, decodePosition, decodeUserStats,
  ixInitializePool, ixStake, ixClaim, ixExit, ixEmergencyWithdraw, ixNotifyReward,
  ixClaimCarried, ixSweep,
  toRaw, fmt, intArg, EARLY_EXIT_PENALTY_BPS, BPS,
  STAKE_VAULT_SEED, REWARD_VAULT_SEED,
  MIN_LOCK_SECS, MAX_LOCK_SECS, REWARDS_DURATION_SECS,
} from './bayla-ladder-ops.mjs';

const PROGRAM = new PublicKey('GKwgTQtVyPGxspxvciDAStY4Jq7rB1STuVvXic7EG6E4');
const MINT = new PublicKey('7hmVkPXmVagxoptAEpx4jBzZVHwGLdFj6c1y42qxpump');
const OWNER = new PublicKey('ASLXdST48ivBZ4xV7VjgD51FJ6rHH5CN5s8XS5TLwygP');
const b = (u8) => Array.from(u8);

describe('instruction discriminators — read off the real IDL', () => {
  // These are the IDL's own bytes, transcribed. If Anchor's derivation ever
  // changed, or an instruction were renamed, the literal is what catches it —
  // recomputing sha256 on both sides would agree with itself and prove nothing.
  const FROM_IDL = {
    initializePool: [95, 180, 10, 172, 84, 174, 232, 40],
    stake: [206, 176, 202, 18, 200, 209, 179, 108],
    claim: [62, 198, 214, 193, 213, 159, 108, 210],
    withdrawMatured: [250, 148, 159, 141, 164, 95, 1, 80],
    earlyExit: [57, 50, 147, 224, 231, 173, 36, 75],
    emergencyWithdraw: [239, 45, 203, 64, 150, 73, 218, 92],
    claimCarried: [173, 173, 45, 126, 170, 32, 215, 248],
    notifyReward: [252, 51, 75, 132, 223, 48, 177, 213],
  };
  for (const [name, want] of Object.entries(FROM_IDL)) {
    it(`${name} matches the IDL`, () => expect(b(IX[name])).toEqual(want));
  }

  it('account discriminators match the IDL', () => {
    expect(b(ACCT.Pool)).toEqual([241, 154, 109, 4, 17, 177, 109, 188]);
    expect(b(ACCT.Position)).toEqual([170, 188, 143, 228, 122, 64, 247, 208]);
    expect(b(ACCT.UserStats)).toEqual([176, 223, 136, 27, 122, 79, 32, 227]);
  });

  it('the derivation routine also reproduces a DIFFERENT program committed table', () => {
    // Cross-check on tegridy-launch's committed values (curve/program.ts): if the
    // routine is wrong it is wrong everywhere, and this catches it without the
    // ladder's own numbers being the only witness.
    const d = (n) => b(createHash('sha256').update(`global:${n}`).digest().subarray(0, 8));
    expect(d('buy')).toEqual([102, 6, 61, 18, 1, 218, 235, 234]);
    expect(d('migrate_to_amm')).toEqual([207, 82, 192, 145, 254, 207, 145, 223]);
  });
});

describe('account layouts', () => {
  // The program pins these three sizes as literals in its own Rust test
  // (`account_sizes_are_pinned`). Every offset table here was hand-summed and
  // must land on the same totals — that agreement is what makes the offsets
  // trustworthy, since a decoder that is wrong by one byte still "works".
  it('total sizes are the ones the program pins', () => {
    expect(POOL_L.SIZE).toBe(508);
    expect(POSITION_L.SIZE).toBe(205);
    expect(USER_L.SIZE).toBe(126);
  });

  // PIN THE TABLE, NOT ITS SHAPE.
  //
  // The previous version asserted only that offsets ascend and sit in bounds. A
  // uniformly shifted table passes that, and so does any wrong-but-ascending one --
  // and a decoder off by one byte still returns a number, so nothing else notices.
  // These expected offsets are rebuilt INDEPENDENTLY here by summing a
  // [field, byteSize] list transcribed from state.rs in declaration order, so the
  // test and the implementation are two separate derivations that must agree.
  const sizesToOffsets = (fields) => {
    const out = {}; let off = 8;             // 8 = anchor discriminator
    // `_reserved` counts toward SIZE but is never decoded, so it carries no offset
    // entry — the upgrade padding is deliberately opaque to the client.
    for (const [name, size] of fields) { if (name !== '_reserved') out[name] = off; off += size; }
    out.SIZE = off; return out;
  };
  const K = 32, U64 = 8, U128 = 16, I64 = 8, U32 = 4, U8 = 1;

  it('Pool offsets match an independent sum of state.rs', () => {
    expect(POOL_L).toEqual(sizesToOffsets([
      ['bump', U8], ['nonce', U8], ['mint', K], ['tokenProgram', K], ['decimals', U8],
      ['authority', K], ['pendingAuthority', K], ['stakeVault', K], ['rewardVault', K],
      ['minStake', U64], ['depositCap', U64], ['pendingCap', U64], ['pendingCapTs', I64],
      ['maxWalletPrincipal', U64], ['totalPrincipal', U64], ['totalWeighted', U128],
      ['rewardRate', U128], ['periodFinish', I64], ['lastUpdateTime', I64],
      ['rewardPerWeightStored', U128], ['rewardsEmitted', U128], ['rewardsPaid', U128],
      ['rewardFundedCumulative', U128], ['penaltyCollectedCumulative', U128],
      ['orphanedPenalty', U64], ['degraded', U8], ['rpwResidue', U128],
      ['emittedResidue', U128], ['_reserved', 88],
    ]));
  });

  it('Position offsets match an independent sum of state.rs', () => {
    expect(POSITION_L).toEqual(sizesToOffsets([
      ['bump', U8], ['pool', K], ['owner', K], ['nonce', U32], ['amount', U64],
      ['weight', U128], ['lockEnd', I64], ['rewardPerWeightPaid', U128],
      ['rewardsOwed', U128], ['_reserved', 64],
    ]));
  });

  it('UserStats offsets match an independent sum of state.rs', () => {
    expect(USER_L).toEqual(sizesToOffsets([
      ['bump', U8], ['pool', K], ['owner', K], ['nextNonce', U32], ['openPositions', U8],
      ['rewardsCarried', U128], ['principal', U64], ['_reserved', 24],
    ]));
  });
});

describe('decoders refuse rather than invent', () => {
  const good = (disc, size) => { const d = Buffer.alloc(size); Buffer.from(disc).copy(d, 0); return d; };

  it('a missing account is a REASON, never a zeroed struct', () => {
    expect(decodePool(null)).toMatchObject({ ok: false });
    expect(decodePosition(undefined)).toMatchObject({ ok: false });
    expect(decodeUserStats(null).reason).toMatch(/never staked|missing/);
  });

  it('a wrong-length buffer is refused', () => {
    expect(decodePool(good(ACCT.Pool, 507))).toMatchObject({ ok: false, reason: expect.stringMatching(/bad-length/) });
  });

  it('another account type is refused on its discriminator', () => {
    // A Position blob padded to Pool's length must NOT decode as a Pool.
    expect(decodePool(good(ACCT.Position, POOL_L.SIZE)))
      .toMatchObject({ ok: false, reason: expect.stringMatching(/wrong-discriminator/) });
  });

  it('a `degraded` byte that is neither 0 nor 1 is malformed, not `true`', () => {
    const d = good(ACCT.Pool, POOL_L.SIZE);
    d[POOL_L.degraded] = 7;
    expect(decodePool(d)).toMatchObject({ ok: false, reason: expect.stringMatching(/malformed/) });
  });
});

describe('PDAs', () => {
  const pool = poolPda(PROGRAM, MINT, 0);

  it('a pool is seeded on (mint, nonce), so the nonce moves it', () => {
    expect(poolPda(PROGRAM, MINT, 1).toBase58()).not.toBe(pool.toBase58());
  });

  it('the two vaults are distinct — separate vaults ARE invariant I-12', () => {
    const sv = vaultPda(PROGRAM, STAKE_VAULT_SEED, pool);
    const rv = vaultPda(PROGRAM, REWARD_VAULT_SEED, pool);
    expect(sv.toBase58()).not.toBe(rv.toBase58());
  });

  it('a position is seeded on a u32 LE nonce, so #0 and #1 differ', () => {
    expect(positionPda(PROGRAM, pool, OWNER, 0).toBase58())
      .not.toBe(positionPda(PROGRAM, pool, OWNER, 1).toBase58());
  });

  it('user stats are per (pool, owner)', () => {
    expect(userPda(PROGRAM, pool, OWNER).toBase58())
      .not.toBe(userPda(PROGRAM, poolPda(PROGRAM, MINT, 1), OWNER).toBase58());
  });
});

describe('instruction builders — account ORDER and FLAGS, straight from the IDL', () => {
  const pool = poolPda(PROGRAM, MINT, 0);
  const p = {
    mint: MINT,
    tokenProgram: new PublicKey('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'),
    stakeVault: vaultPda(PROGRAM, STAKE_VAULT_SEED, pool),
    rewardVault: vaultPda(PROGRAM, REWARD_VAULT_SEED, pool),
  };
  // Anchor matches accounts by POSITION. `S` = signer, `W` = writable, exactly as
  // the IDL reports them.
  const shape = (ix) => ix.keys.map((k) => `${k.isSigner ? 'S' : ''}${k.isWritable ? 'W' : ''}`);

  // NAMED positions, not just flags.
  //
  // MUTATION-CHECKED AND FOUND WANTING: swapping `user_stats` and `position` in
  // `ixStake` left all 31 tests green, because both are (non-signer, writable) so
  // `shape()` is byte-identical across the swap. A reordered account list is the
  // exact failure this suite exists to catch — it surfaces on-chain as a
  // constraint violation on the wrong account, which reads like a program bug.
  // Flags alone cannot see it; the addresses can.
  const SYSTEM = '11111111111111111111111111111111';
  const named = {
    owner: OWNER.toBase58(),
    pool: pool.toBase58(),
    mint: MINT.toBase58(),
    tokenProgram: p.tokenProgram.toBase58(),
    stakeVault: p.stakeVault.toBase58(),
    rewardVault: p.rewardVault.toBase58(),
    userStats: userPda(PROGRAM, pool, OWNER).toBase58(),
    position0: positionPda(PROGRAM, pool, OWNER, 0).toBase58(),
    system: SYSTEM,
  };
  const label = (k) =>
    Object.entries(named).find(([, v]) => v === k.pubkey.toBase58())?.[0] ?? `other(${k.pubkey.toBase58().slice(0, 6)})`;
  const order = (ix) => ix.keys.map(label);

  it('initialize_pool', () => {
    const ix = ixInitializePool({
      programId: PROGRAM, payer: OWNER, mint: MINT, tokenProgram: p.tokenProgram,
      nonce: 0, minStake: 1n, depositCap: 2n, maxWallet: 2n,
    });
    expect(shape(ix)).toEqual(['SW', '', 'W', 'W', 'W', '', '']);
    expect(order(ix)).toEqual(['owner', 'mint', 'pool', 'stakeVault', 'rewardVault', 'tokenProgram', 'system']);
    expect(b(ix.data.subarray(0, 8))).toEqual(b(IX.initializePool));
    // nonce u8 + three u64 = 25 bytes of args
    expect(ix.data.length).toBe(8 + 1 + 8 * 3);
  });

  it('stake', () => {
    const ix = ixStake({ programId: PROGRAM, owner: OWNER, pool, p, positionNonce: 0, amountRaw: 1n, lockSecs: MIN_LOCK_SECS });
    expect(shape(ix)).toEqual(['SW', 'W', '', 'W', 'W', 'W', 'W', '', '']);
    expect(order(ix)).toEqual(['owner', 'pool', 'mint', 'userStats', 'position0', 'other(ata)', 'stakeVault', 'tokenProgram', 'system']
      .map((x) => (x === 'other(ata)' ? order(ix)[5] : x)));
    // position 4 must be the POSITION and 3 the USER STATS, never swapped
    expect(order(ix)[3]).toBe('userStats');
    expect(order(ix)[4]).toBe('position0');
    expect(ix.data.length).toBe(8 + 8 + 8);
    expect(ix.data.readBigInt64LE(16)).toBe(BigInt(MIN_LOCK_SECS));
  });

  it('claim — the owner signs but is NOT writable', () => {
    const ix = ixClaim({ programId: PROGRAM, owner: OWNER, pool, p, positionNonce: 0 });
    expect(shape(ix)).toEqual(['S', 'W', '', 'W', 'W', 'W', '']);
    expect(order(ix)[3]).toBe('position0');
    expect(order(ix)[5]).toBe('rewardVault');
  });

  it('the two exit doors share an account list and differ ONLY in discriminator', () => {
    const a = ixExit({ programId: PROGRAM, owner: OWNER, pool, p, positionNonce: 0, early: false });
    const c = ixExit({ programId: PROGRAM, owner: OWNER, pool, p, positionNonce: 0, early: true });
    expect(shape(a)).toEqual(['SW', 'W', '', 'W', 'W', 'W', 'W', 'W', '']);
    expect(order(a)[3]).toBe('userStats');
    expect(order(a)[4]).toBe('position0');
    expect(order(a)[6]).toBe('stakeVault');
    expect(order(a)[7]).toBe('rewardVault');
    expect(shape(c)).toEqual(shape(a));
    expect(a.keys.map((k) => k.pubkey.toBase58())).toEqual(c.keys.map((k) => k.pubkey.toBase58()));
    expect(b(a.data)).toEqual(b(IX.withdrawMatured));
    expect(b(c.data)).toEqual(b(IX.earlyExit));
  });

  it('the hatch NAMES NO REWARD VAULT — invariant I-12, structural', () => {
    const ix = ixEmergencyWithdraw({ programId: PROGRAM, owner: OWNER, pool, p, positionNonce: 0 });
    expect(shape(ix)).toEqual(['SW', 'W', '', 'W', 'W', 'W', 'W', '']);
    expect(order(ix)[3]).toBe('userStats');
    expect(order(ix)[4]).toBe('position0');
    const named = ix.keys.map((k) => k.pubkey.toBase58());
    expect(named).not.toContain(p.rewardVault.toBase58());
    expect(named).toContain(p.stakeVault.toBase58());
  });

  it('notify_reward — the authority signs but is NOT writable', () => {
    const ix = ixNotifyReward({ programId: PROGRAM, authority: OWNER, pool, p, amountRaw: 5n, fromBudgetRaw: 7n });
    expect(shape(ix)).toEqual(['S', 'W', '', 'W', 'W', '']);
    expect(order(ix)[4]).toBe('rewardVault');
    expect(ix.data.readBigUInt64LE(8)).toBe(5n);
    expect(ix.data.readBigUInt64LE(16)).toBe(7n);
  });
});

describe('amounts', () => {
  it('whole tokens convert on the MINT decimals, exactly', () => {
    expect(toRaw('1', 6)).toBe(1_000_000n);
    expect(toRaw('0.5', 6)).toBe(500_000n);
    expect(toRaw('1234.567891', 6)).toBe(1_234_567_891n);
  });

  it('REFUSES more precision than the mint has, rather than truncating silently', () => {
    // Truncating here would under-stake by a rounding error the user never sees.
    expect(() => toRaw('1.1234567', 6)).toThrow(/decimal places/);
  });

  it('refuses junk instead of coercing it to zero', () => {
    for (const bad of ['', 'abc', '-1', '1e6', '1.2.3']) expect(() => toRaw(bad, 6)).toThrow();
  });

  it('formats without floats, and an unreadable value is a dash', () => {
    expect(fmt(1_234_567_891n, 6)).toBe('1,234.567891');
    expect(fmt(null, 6)).toBe('—');
    expect(fmt(0n, 6)).toBe('0');
  });
});

describe('the constants quoted from math.rs', () => {
  it('are the program bounds, so a bad request is refused locally', () => {
    expect(MIN_LOCK_SECS).toBe(7 * 86_400);
    expect(MAX_LOCK_SECS).toBe(4 * 365 * 86_400);
    expect(REWARDS_DURATION_SECS).toBe(90 * 86_400);
  });
});

describe('decoders read the RIGHT field at the RIGHT width', () => {
  // The refusal tests above only ever assert ok/reason, so a decoder that read
  // `minStake` from `depositCap`'s offset, or used a u64 read where the struct has
  // a u128, passed every one of them. This builds a buffer with a DISTINCT value
  // per field at offsets transcribed by hand from state.rs (deliberately literal,
  // so this is a second derivation rather than a restatement of POOL_L), then
  // asserts every decoded field individually.
  const K = (byte) => Buffer.alloc(32, byte);
  const put = (buf, off, bytes) => Buffer.from(bytes).copy(buf, off);
  const u64at = (buf, off, v) => buf.writeBigUInt64LE(BigInt(v), off);
  const i64at = (buf, off, v) => buf.writeBigInt64LE(BigInt(v), off);
  // u128 LE = low 8 bytes, then high 8 bytes
  const u128at = (buf, off, v) => {
    buf.writeBigUInt64LE(BigInt(v) & 0xffffffffffffffffn, off);
    buf.writeBigUInt64LE(BigInt(v) >> 64n, off + 8);
  };

  it('Pool: every field comes back from its own offset, at its own width', () => {
    const d = Buffer.alloc(508);
    put(d, 0, ACCT.Pool);
    d[8] = 254;
    d[9] = 3;
    put(d, 10, K(0x11));
    put(d, 42, K(0x22));
    d[74] = 6;
    put(d, 75, K(0x33));
    put(d, 107, K(0x44));
    put(d, 139, K(0x55));
    put(d, 171, K(0x66));
    u64at(d, 203, 100000000);
    u64at(d, 211, 999000000);
    u64at(d, 219, 5);
    i64at(d, 227, -7);
    u64at(d, 235, 42000000);
    u64at(d, 243, 777);
    u128at(d, 251, (1n << 70n) + 5n);
    u128at(d, 267, (1n << 68n) + 9n);
    i64at(d, 283, 1700000000);
    i64at(d, 291, 1600000000);
    u128at(d, 315, (1n << 66n) + 1n);
    u128at(d, 331, 123n);
    u128at(d, 347, 456n);
    u128at(d, 363, 789n);
    u64at(d, 379, 31337);
    d[387] = 1;

    const r = decodePool(d);
    expect(r.ok).toBe(true);
    const v = r.value;
    expect(v.bump).toBe(254);
    expect(v.nonce).toBe(3);
    expect(v.mint.toBuffer()).toEqual(K(0x11));
    expect(v.tokenProgram.toBuffer()).toEqual(K(0x22));
    expect(v.decimals).toBe(6);
    expect(v.authority.toBuffer()).toEqual(K(0x33));
    expect(v.pendingAuthority.toBuffer()).toEqual(K(0x44));
    expect(v.stakeVault.toBuffer()).toEqual(K(0x55));
    expect(v.rewardVault.toBuffer()).toEqual(K(0x66));
    expect(v.minStake).toBe(100000000n);
    expect(v.depositCap).toBe(999000000n);
    expect(v.pendingCap).toBe(5n);
    expect(v.pendingCapTs).toBe(-7n);
    expect(v.maxWalletPrincipal).toBe(42000000n);
    expect(v.totalPrincipal).toBe(777n);
    expect(v.totalWeighted).toBe((1n << 70n) + 5n);
    expect(v.rewardRate).toBe((1n << 68n) + 9n);
    expect(v.periodFinish).toBe(1700000000n);
    expect(v.lastUpdateTime).toBe(1600000000n);
    expect(v.rewardsEmitted).toBe((1n << 66n) + 1n);
    expect(v.rewardsPaid).toBe(123n);
    expect(v.rewardFundedCumulative).toBe(456n);
    expect(v.penaltyCollectedCumulative).toBe(789n);
    expect(v.orphanedPenalty).toBe(31337n);
    expect(v.degraded).toBe(true);
  });

  it('Position: every field comes back from its own offset', () => {
    const d = Buffer.alloc(205);
    put(d, 0, ACCT.Position);
    put(d, 9, K(0x77));
    put(d, 41, K(0x88));
    d.writeUInt32LE(9, 73);
    u64at(d, 77, 500000000);
    u128at(d, 85, (1n << 65n) + 3n);
    i64at(d, 101, 1800000000);
    u128at(d, 125, 4242n);
    const r = decodePosition(d);
    expect(r.ok).toBe(true);
    expect(r.value.pool.toBuffer()).toEqual(K(0x77));
    expect(r.value.owner.toBuffer()).toEqual(K(0x88));
    expect(r.value.nonce).toBe(9);
    expect(r.value.amount).toBe(500000000n);
    expect(r.value.weight).toBe((1n << 65n) + 3n);
    expect(r.value.lockEnd).toBe(1800000000n);
    expect(r.value.rewardsOwed).toBe(4242n);
  });

  it('UserStats: every field comes back from its own offset', () => {
    const d = Buffer.alloc(126);
    put(d, 0, ACCT.UserStats);
    d.writeUInt32LE(4, 73);
    d[77] = 2;
    u128at(d, 78, 9000n);
    u64at(d, 94, 12345n);
    const r = decodeUserStats(d);
    expect(r.ok).toBe(true);
    expect(r.value.nextNonce).toBe(4);
    expect(r.value.openPositions).toBe(2);
    expect(r.value.rewardsCarried).toBe(9000n);
    expect(r.value.principal).toBe(12345n);
  });
});

describe('the two commands that had no builder at all', () => {
  const pool = poolPda(PROGRAM, MINT, 0);
  const p = {
    mint: MINT,
    tokenProgram: new PublicKey('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'),
    stakeVault: vaultPda(PROGRAM, STAKE_VAULT_SEED, pool),
    rewardVault: vaultPda(PROGRAM, REWARD_VAULT_SEED, pool),
  };
  const shp = (ix) => ix.keys.map((k) => (k.isSigner ? 'S' : '') + (k.isWritable ? 'W' : ''));

  it('claim_carried matches the IDL and names NO stake vault', () => {
    const ix = ixClaimCarried({ programId: PROGRAM, owner: OWNER, pool, p });
    expect(shp(ix)).toEqual(['S', 'W', '', 'W', 'W', 'W', '']);
    expect(b(ix.data)).toEqual([173, 173, 45, 126, 170, 32, 215, 248]);
    const named = ix.keys.map((k) => k.pubkey.toBase58());
    // Paid from the REWARD vault only: principal is never a reward source (I-12).
    expect(named).toContain(p.rewardVault.toBase58());
    expect(named).not.toContain(p.stakeVault.toBase58());
  });

  it('sweep is PERMISSIONLESS — it declares no signer at all', () => {
    const ix = ixSweep({ programId: PROGRAM, pool, p });
    expect(shp(ix)).toEqual(['W', '', 'W', 'W', '']);
    expect(ix.keys.some((k) => k.isSigner)).toBe(false);
    expect(ix.keys.map((k) => k.pubkey.toBase58())).toEqual([
      pool.toBase58(), MINT.toBase58(), p.stakeVault.toBase58(),
      p.rewardVault.toBase58(), p.tokenProgram.toBase58(),
    ]);
  });
});

describe('the hatch penalty the CLI now prints', () => {
  // lib.rs:607-613 — emergency_withdraw charges penalty_for(amount) when
  // `now < lock_end && !degraded`. math.rs floors amount * 2500 / 10000.
  // The CLI claimed "no penalty" unconditionally until this was caught.
  const pen = (amount) => (BigInt(amount) * BigInt(EARLY_EXIT_PENALTY_BPS)) / BigInt(BPS);

  it('is 25%, floored, exactly as math.rs computes it', () => {
    expect(EARLY_EXIT_PENALTY_BPS).toBe(2500);
    expect(BPS).toBe(10000);
    expect(pen(1000000)).toBe(250000n);
    expect(pen(3)).toBe(0n);
    expect(pen(7)).toBe(1n);
  });
});

describe('intArg refuses what silently became position #0', () => {
  // Number('') is 0 and Number('abc') is NaN, and writeUInt32LE encodes BOTH as
  // zero — so an unset shell variable addressed the first, usually largest position.
  for (const bad of ['', 'abc', '-1', '1.5', 'NaN', '4294967296', '0x10', ' 1 2']) {
    it('refuses ' + JSON.stringify(bad), () => {
      expect(() => intArg({ nonce: bad }, 'nonce')).toThrow();
    });
  }
  it('accepts real nonces', () => {
    expect(intArg({ nonce: '0' }, 'nonce')).toBe(0);
    expect(intArg({ nonce: '4294967295' }, 'nonce')).toBe(4294967295);
  });
});
