// GENERATED by frontend/scripts/capture-airlock-selectors.mjs — DO NOT EDIT BY HAND.
//
// The function selectors the deployed Doppler Airlock actually implements, captured
// from its runtime BYTECODE (not from the SDK, whose airlockAbi is stale — it still
// names the fee accessor `integratorFees`, which this contract does not have).
//
// airlockSelectors.test.ts asserts every function our hand-rolled Airlock ABI
// fragments declare appears here. Regenerate only by re-running the script; editing
// this file by hand to make a test pass would defeat its entire purpose.
//
// Airlock: 0xde3599a2ec440b296373a983c85c365da55d9dfa
// Captured at block 25650362 (mainnet).

/** The Airlock this fixture describes. Must match DOPPLER_MAINNET.airlock. */
export const AIRLOCK_ADDRESS = '0xde3599a2ec440b296373a983c85c365da55d9dfa' as const;

/** Mainnet block the capture was taken at. */
export const CAPTURED_AT_BLOCK = 25650362;

/**
 * Every PUSH4 immediate in an opcode-honouring walk of the runtime bytecode.
 * A function the contract implements ALWAYS appears here (solc's dispatcher compares
 * against PUSH4 constants). The converse does not hold — selectors the Airlock calls
 * on other contracts also appear — so this is a necessary, not sufficient, condition.
 */
export const AIRLOCK_DEPLOYED_SELECTORS: ReadonlySet<string> = new Set([
  '0x067bab61',
  '0x095ea7b3',
  '0x103e831b',
  '0x11204ca7',
  '0x118cdaa7',
  '0x1285e1ce',
  '0x1652e7b7',
  '0x1dc00523',
  '0x1e4fbdf7',
  '0x2208bb05',
  '0x2e27c8de',
  '0x2f62ed99',
  '0x34d1a365',
  '0x4e487b71',
  '0x51fb4bdd',
  '0x70a08231',
  '0x715018a6',
  '0x8161b874',
  '0x8539c821',
  '0x882db707',
  '0x8da5cb5b',
  '0xa9059cbb',
  '0xb5d97103',
  '0xce5494bb',
  '0xcf7a1d77',
  '0xe7f0d8f1',
  '0xf27dd8ab',
  '0xf2fde38b',
]);

/**
 * Selectors PROVEN to dispatch by a live eth_call that returned data. Positive proof
 * of implementation, and the signal that actually distinguishes getIntegratorFees
 * (returns a uint256 word) from the absent integratorFees (reverts). View functions
 * only — a nonpayable function reverts on its own preconditions and cannot be probed
 * this way, so absence from this set means "not probed", never "not implemented".
 */
export const AIRLOCK_DISPATCHED_SELECTORS: ReadonlySet<string> = new Set([
  '0xe7f0d8f1',
  '0x2e27c8de',
  '0x8da5cb5b',
  '0x1652e7b7',
]);
