import { useState, useEffect } from 'react';
import { m, AnimatePresence } from 'framer-motion';
import { ART } from '../lib/artConfig';
import { usePageTitle } from '../hooks/usePageTitle';
import { FAQ_INTRO } from '../lib/copy';

interface FAQItem {
  q: string;
  a: string;
}

interface FAQSection {
  category: string;
  items: FAQItem[];
}

const FAQ_DATA: FAQSection[] = [
  {
    category: 'Getting Started',
    items: [
      { q: 'What is Tegridy Farms?', a: 'Tegridy Farms is a yield farming protocol on Ethereum. Stake TOWELI tokens to earn rewards from the protocol. 100% of swap fees generated by the Tegridy DEX are distributed to stakers.' },
      { q: 'How do I get TOWELI tokens?', a: 'Buy TOWELI on Uniswap V2. Simply swap ETH for TOWELI at app.uniswap.org. Make sure you are connected to Ethereum Mainnet.' },
      { q: 'What wallets are supported?', a: 'MetaMask, WalletConnect, Coinbase Wallet, and most Ethereum wallets are supported via RainbowKit. Any wallet that supports Ethereum Mainnet should work.' },
      { q: 'What network does Tegridy Farms run on?', a: 'Ethereum Mainnet only. Make sure your wallet is connected to the correct network before interacting with the protocol.' },
    ],
  },
  {
    category: 'Staking',
    items: [
      { q: 'How does staking work?', a: 'Deposit TOWELI tokens into the staking contract to earn ETH rewards from swap fees. Choose a lock duration to receive a boost multiplier — longer locks earn higher yields.' },
      { q: 'What is the lock duration?', a: 'You can lock your TOWELI for 1 to 52 months. Longer lock durations give you a higher boost multiplier, which means more rewards.' },
      { q: 'Can I withdraw early?', a: 'Yes, but with a 25% early withdrawal penalty. The penalty amount is distributed proportionally to all remaining stakers as a bonus.' },
      { q: 'What is a boost multiplier?', a: 'Your lock duration determines your yield boost. 1 month lock = 1x multiplier, scaling up to 2.5x at 52 months. Higher multipliers mean a larger share of the reward pool.' },
      { q: 'Do I get an NFT for staking?', a: 'Yes. Your staking position is represented as an ERC-721 NFT. This NFT tracks your deposit amount, lock duration, and boost. It can also be used as collateral for peer-to-peer lending.' },
      { q: 'What are NFT boosts?', a: 'Holders of JBAC, Nakamigos, or GNSS NFTs receive an additional 10-20% yield boost on top of their lock multiplier. Simply hold the NFT in your connected wallet to activate the bonus.' },
    ],
  },
  {
    category: 'Rewards',
    items: [
      { q: 'Where do rewards come from?', a: '100% of swap fees generated by the Tegridy DEX are collected by the RevenueDistributor contract and distributed to TOWELI stakers as ETH.' },
      { q: 'How often can I claim rewards?', a: 'Anytime. Rewards accrue continuously in real-time and can be claimed whenever you want with no minimum threshold.' },
      { q: 'What is the Tegridy Score?', a: 'A points system based on your on-chain activity — staking, swapping, voting, and referrals all earn points. Higher scores unlock tier benefits and leaderboard rankings.' },
    ],
  },
  {
    category: 'NFT Finance',
    items: [
      { q: 'What is NFT Lending?', a: 'Borrow ETH by locking your NFTs (JBAC, Nakamigos, GNSS) as collateral. It is fully peer-to-peer with no oracles and no liquidation auctions.' },
      { q: 'What happens if I default on a loan?', a: 'The lender claims your NFT permanently. There is no liquidation auction — the NFT simply transfers to the lender after the loan expires unpaid.' },
      { q: 'What is the NFT AMM?', a: 'Bonding curve pools for instant NFT trading. Provide liquidity by depositing NFTs and ETH into a pool to earn fees on every trade that occurs in that pool.' },
      { q: 'What is pro-rata interest?', a: 'Interest is calculated based on the actual time borrowed, not the full loan term. If you repay early, you pay proportionally less interest than the maximum.' },
    ],
  },
  {
    category: 'Security',
    items: [
      { q: 'Are the contracts audited?', a: 'The contracts have undergone extensive internal security review including red team testing, fuzz testing, and invariant testing. Visit the Security page for full details and test results.' },
      { q: 'Can the admin rug pull?', a: 'No. All admin parameter changes are enforced through a timelock of 24-48 hours. Users always have time to review changes and exit their positions before any modification takes effect.' },
      { q: 'What are the risks?', a: 'Smart contract risk, market volatility, impermanent loss for liquidity providers, and early withdrawal penalties. Always do your own research and never invest more than you can afford to lose.' },
    ],
  },
  {
    category: 'Premium',
    items: [
      { q: 'What is the Gold Card?', a: 'The Gold Card is a premium tier that grants 3x points multiplier, priority access to new features, and exclusive benefits. It is paid monthly in ETH.' },
      { q: 'Do JBAC holders get free access?', a: 'Yes. JBAC NFT holders receive lifetime Gold Card access at no cost. Simply hold a JBAC in your connected wallet to activate premium benefits.' },
    ],
  },
];

export default function FAQPage() {
  usePageTitle('FAQ', 'Frequently asked questions about Tegridy Farms');
  const [openIndex, setOpenIndex] = useState<string | null>(null);
  const [search, setSearch] = useState('');

  // Inject FAQPage structured data for SEO rich results
  useEffect(() => {
    const allItems = FAQ_DATA.flatMap(s => s.items);
    const jsonLd = {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: allItems.map(item => ({
        '@type': 'Question',
        name: item.q,
        acceptedAnswer: { '@type': 'Answer', text: item.a },
      })),
    };
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.textContent = JSON.stringify(jsonLd);
    document.head.appendChild(script);
    return () => { document.head.removeChild(script); };
  }, []);

  const toggle = (key: string) => setOpenIndex(openIndex === key ? null : key);

  const filtered = FAQ_DATA.map((section) => ({
    ...section,
    items: section.items.filter(
      (item) =>
        item.q.toLowerCase().includes(search.toLowerCase()) ||
        item.a.toLowerCase().includes(search.toLowerCase())
    ),
  })).filter((section) => section.items.length > 0);

  return (
    <div className="-mt-14 relative min-h-screen">
      <div className="fixed inset-0 z-0" style={{ background: '#060c1a' }}>
        <img src={ART.bobowelie.src} alt="" loading="lazy" className="w-full h-full object-cover" />
      </div>

      <div className="relative z-10 max-w-[800px] mx-auto px-4 md:px-6 pt-32 pb-20">
        {/* Header */}
        <m.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-10"
        >
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-3">
            {FAQ_INTRO.headline}
          </h1>
          <p className="text-gray-400 text-sm md:text-base max-w-[600px] mx-auto">
            {FAQ_INTRO.subheading}
          </p>
        </m.div>

        {/* Search */}
        <m.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-8"
        >
          <div
            className="rounded-xl px-4 py-3 flex items-center gap-3"
            style={{ background: 'rgba(13, 21, 48, 0.6)', border: '1px solid var(--color-purple-12)' }}
          >
            <svg className="w-5 h-5 text-gray-500 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input
              type="text"
              placeholder="Search questions..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="bg-transparent w-full text-white placeholder-gray-500 outline-none text-[16px]"
            />
            {search && (
              <button onClick={() => setSearch('')} aria-label="Clear search" className="text-gray-500 hover:text-white text-lg leading-none">
                &times;
              </button>
            )}
          </div>
        </m.div>

        {/* FAQ Sections */}
        {filtered.length === 0 && (
          <div className="text-center text-gray-500 py-16 text-sm">
            No questions match your search.
          </div>
        )}

        {filtered.map((section, sIdx) => (
          <m.div
            key={section.category}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.15 + sIdx * 0.05 }}
            className="mb-6"
          >
            <h2 className="text-purple-400 text-xs font-semibold uppercase tracking-widest mb-3 px-1">
              {section.category}
            </h2>
            <div
              className="rounded-xl overflow-hidden divide-y divide-white/5"
              style={{ background: 'rgba(13, 21, 48, 0.6)', border: '1px solid var(--color-purple-12)' }}
            >
              {section.items.map((item, qIdx) => {
                const key = `${sIdx}-${qIdx}`;
                const isOpen = openIndex === key;
                return (
                  <div key={key}>
                    <button
                      onClick={() => toggle(key)}
                      className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left hover:bg-white/[0.03] transition-colors"
                    >
                      <span className="text-white text-sm font-medium leading-snug">{item.q}</span>
                      <m.svg
                        animate={{ rotate: isOpen ? 180 : 0 }}
                        transition={{ duration: 0.25 }}
                        className="w-4 h-4 text-purple-400 shrink-0"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                      </m.svg>
                    </button>
                    <AnimatePresence initial={false}>
                      {isOpen && (
                        <m.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.25, ease: 'easeInOut' }}
                          className="overflow-hidden"
                        >
                          <div className="px-5 pb-4 text-gray-400 text-sm leading-relaxed">
                            {item.a}
                          </div>
                        </m.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })}
            </div>
          </m.div>
        ))}
      </div>
    </div>
  );
}
