/**
 * Per-surface art overrides — written by /art-studio.
 *
 * Key format: `${pageId}:${idx}` (matches pageArt(pageId, idx) call sites).
 * `artId` must match an `id` in ART (see artConfig.ts).
 * `objectPosition` is a CSS object-position string (e.g. "center 30%", "50% 20%").
 *
 * Surfaces NOT listed here fall back to the deterministic rotation in pageArt().
 *
 * Do not hand-edit during a studio session — the studio overwrites this file on save.
 */
export type ArtOverride = {
  artId: string;
  objectPosition?: string;
  scale?: number;
};

export const ART_OVERRIDES: Record<string, ArtOverride> = {
  // Chrome art (loader splash rotation + page-transition frames + nav logo + token icon)
  "nav-logo:0": { artId: "bobowelie" },
  "token-icon:0": { artId: "bobowelie" },
  "loader:0": { artId: "mfers-heaven" },
  "loader:1": { artId: "mumu-bull" },
  "loader:2": { artId: "bobowelie" },
  "loader:3": { artId: "jungle-bus" },
  "loader:4": { artId: "pool-party" },
  "loader:5": { artId: "boxing-ring" },
  "loader:6": { artId: "forest-scene" },
  "loader:7": { artId: "chaos-scene" },
  "loader:8": { artId: "ape-hug" },
  "loader:9": { artId: "beach-vibes" },
  "loader:10": { artId: "dance-night" },
  "loader:11": { artId: "wrestler" },
  "loader:12": { artId: "smoking-duo" },
  "loader:13": { artId: "beach-sunset" },
  "loader:14": { artId: "porch-chill" },
  "loader:15": { artId: "rose-ape" },
  "loader:16": { artId: "sword-of-love" },
  "loader:17": { artId: "towelie-window" },
  "loader:18": { artId: "bus-crew" },
  "loader:19": { artId: "gallery-collage" },
  "loader:20": { artId: "jungle-dark" },
  "loader:21": { artId: "jb-christmas" },
  "loader:22": { artId: "naka07" },
  "loader:23": { artId: "naka09" },
  "loader:24": { artId: "naka30" },
  "loader:25": { artId: "naka29" },
  "loader:26": { artId: "naka24" },
  "loader:27": { artId: "naka06" },
  "loader:28": { artId: "naka27" },
  "loader:29": { artId: "naka05" },
  "loader:30": { artId: "naka25" },
  "loader:31": { artId: "naka20" },
  "loader:32": { artId: "naka28" },
  "loader:33": { artId: "naka01" },
  "loader:34": { artId: "naka19" },
  "loader:35": { artId: "naka22" },
  "loader:36": { artId: "naka02" },
  "loader:37": { artId: "naka21" },
  "loader:38": { artId: "naka11" },
  "loader:39": { artId: "naka26" },
  "transition:0": { artId: "mfers-heaven" },
  "transition:1": { artId: "mumu-bull" },
  "transition:2": { artId: "bobowelie" },
  "transition:3": { artId: "jungle-bus" },
  "transition:4": { artId: "pool-party" },
  "transition:5": { artId: "boxing-ring" },
  "transition:6": { artId: "bus-crew" },
  "transition:7": { artId: "forest-scene" },
  "transition:8": { artId: "sword-of-love" },
  "transition:9": { artId: "towelie-window" },
  "transition:10": { artId: "chaos-scene" },
  "transition:11": { artId: "ape-hug" },
  "transition:12": { artId: "beach-vibes" },
  "transition:13": { artId: "dance-night" },
  "transition:14": { artId: "wrestler" },
  "transition:15": { artId: "jungle-dark" },
  "transition:16": { artId: "smoking-duo" },
  "transition:17": { artId: "jb-christmas" },
  "transition:18": { artId: "beach-sunset" },
  "transition:19": { artId: "porch-chill" },
  "transition:20": { artId: "rose-ape" },
  "transition:21": { artId: "naka07" },
  "transition:22": { artId: "naka06" },
  "transition:23": { artId: "naka05" },
  "transition:24": { artId: "naka04" },
  "transition:25": { artId: "naka01" },
  "transition:26": { artId: "naka02" },
  "transition:27": { artId: "naka09" },
  "transition:28": { artId: "naka30" },
  "transition:29": { artId: "naka29" },
  "transition:30": { artId: "naka27" },
  "transition:31": { artId: "naka25" },
  "transition:32": { artId: "naka20" },
  "transition:33": { artId: "naka28" },
  "transition:34": { artId: "naka21" },
  "transition:35": { artId: "naka19" },
  "transition:36": { artId: "naka22" },
  "transition:37": { artId: "naka11" },
  "transition:38": { artId: "naka26" },
  "admin-dashboard:0": { artId: "naka09", objectPosition: "50% 90%" },
  "admin:0": { artId: "naka04", objectPosition: "50% 93%" },
  "amm:0": { artId: "boxing-ring" },
  "amm:1": { artId: "pool-party" },
  "amm:10": { artId: "mumu-bull" },
  "amm:11": { artId: "bus-crew" },
  "amm:12": { artId: "wrestler" },
  "amm:13": { artId: "wrestler" },
  "amm:14": { artId: "bus-crew" },
  "amm:15": { artId: "wrestler" },
  "amm:16": { artId: "pool-party" },
  "amm:17": { artId: "beach-sunset" },
  "amm:18": { artId: "jungle-dark" },
  "amm:2": { artId: "beach-sunset" },
  "amm:3": { artId: "chaos-scene" },
  "amm:4": { artId: "wrestler" },
  "amm:5": { artId: "jungle-dark" },
  "amm:6": { artId: "jungle-dark" },
  "amm:7": { artId: "mumu-bull" },
  "amm:8": { artId: "mumu-bull" },
  "amm:9": { artId: "beach-sunset" },
  "boost-schedule:0": { artId: "splash13", objectPosition: "50% 17%" },
  "boost-schedule:1": { artId: "boxing-ring", objectPosition: "50% 27%" },
  "boost-schedule:2": { artId: "naka19", objectPosition: "50% 76%" },
  "bounties:0": { artId: "beach-sunset", objectPosition: "50% 0%" },
  "bounties:1": { artId: "naka19", objectPosition: "50% 24%" },
  "bounties:2": { artId: "naka07", objectPosition: "50% 50%" },
  "bounties:3": { artId: "iph_0141" },
  "bounties:4": { artId: "bus-crew", objectPosition: "50% 6%" },
  "bounties:5": { artId: "naka03", objectPosition: "50% 93%" },
  "changelog-cards:12": { artId: "naka31", objectPosition: "50% 60%" },
  "changelog-cards:13": { artId: "wrestler", objectPosition: "50% 67%" },
  "changelog-cards:14": { artId: "dance-night", objectPosition: "50% 76%" },
  "changelog-cards:15": { artId: "jungle-bus", objectPosition: "50% 60%" },
  "changelog-cards:2": { artId: "naka21", objectPosition: "50% 0%" },
  "changelog-cards:3": { artId: "naka22", objectPosition: "50% 72%" },
  "changelog-cards:4": { artId: "naka23", objectPosition: "50% 70%" },
  "changelog-cards:6": { artId: "naka25", objectPosition: "50% 0%" },
  "changelog-cards:7": { artId: "naka26", objectPosition: "50% 75%" },
  "changelog-cards:8": { artId: "naka27", objectPosition: "50% 53%" },
  "changelog:0": { artId: "iph_0142" },
  "community:0": { artId: "naka16", objectPosition: "50% 64%" },
  "community:1": { artId: "iph_0132", objectPosition: "50% 5%" },
  "connect-prompt:0": { artId: "card09" },
  "consent-banner:0": { artId: "card05" },
  "dashboard:0": { artId: "naka11", objectPosition: "50% 0%" },
  "dashboard:1": { artId: "iph_0163", objectPosition: "50% 7%" },
  "dashboard:10": { artId: "naka21", objectPosition: "50% 76%" },
  "dashboard:11": { artId: "naka06", objectPosition: "50% 26%" },
  "dashboard:12": { artId: "naka23", objectPosition: "50% 6%" },
  "dashboard:13": { artId: "naka24", objectPosition: "50% 75%" },
  "dashboard:2": { artId: "naka13", objectPosition: "50% 27%" },
  "dashboard:3": { artId: "iph_0162" },
  "dashboard:4": { artId: "pool-party", objectPosition: "50% 49%" },
  "dashboard:5": { artId: "porch-chill", objectPosition: "50% 63%" },
  "dashboard:6": { artId: "iph_0143" },
  "dashboard:7": { artId: "naka10", objectPosition: "50% 11%" },
  "dashboard:8": { artId: "naka19", objectPosition: "50% 76%" },
  "dashboard:9": { artId: "naka20", objectPosition: "50% 74%" },
  "faq:0": { artId: "iph_0156", objectPosition: "50% 54%" },
  "farm-stats:0": { artId: "iph_1063" },
  "farm-stats:1": { artId: "smoking-duo", objectPosition: "50% 38%" },
  "farm-stats:2": { artId: "naka17", objectPosition: "50% 52%" },
  "farm-stats:3": { artId: "naka26", objectPosition: "50% 22%" },
  "farm:0": { artId: "iph_0176", objectPosition: "50% 86%" },
  "farm:1": { artId: "naka08", objectPosition: "50% 86%" },
  "gauge-voting:0": { artId: "iph_0164" },
  "gauge-voting:1": { artId: "iph_0137", objectPosition: "50% 96%" },
  "gauge-voting:2": { artId: "iph_0138", objectPosition: "50% 2%" },
  "gauge-voting:3": { artId: "iph_1059" },
  "gauge-voting:4": { artId: "iph_0174" },
  "gauge-voting:5": { artId: "iph_0133", objectPosition: "50% 62%" },
  "gauge-voting:6": { artId: "iph_0161", objectPosition: "50% 58%" },
  "grants:0": { artId: "iph_0145", objectPosition: "50% 56%" },
  "grants:1": { artId: "iph_0144", objectPosition: "50% 0%" },
  "grants:2": { artId: "chaos-scene", objectPosition: "50% 39%" },
  "grants:3": { artId: "iph_0153", objectPosition: "50% 31%" },
  "history:2": { artId: "iph_1068" },
  "home:0": { artId: "iph_0148", objectPosition: "5% 97%" },
  "home:1": { artId: "jungle-bus", objectPosition: "0% 61%", scale: 1.05 },
  "home:10": { artId: "naka26", objectPosition: "50% 13%" },
  "home:11": { artId: "iph_0175" },
  "home:13": { artId: "naka29", objectPosition: "50% 41%" },
  "home:14": { artId: "naka30", objectPosition: "50% 37%" },
  "home:2": { artId: "naka18", objectPosition: "50% 10%" },
  "home:4": { artId: "naka20", objectPosition: "50% 9%", scale: 1.05 },
  "home:5": { artId: "naka21", objectPosition: "50% 0%" },
  "home:6": { artId: "naka22", objectPosition: "50% 3%" },
  "home:7": { artId: "naka23", objectPosition: "50% 6%" },
  "launchpad-collection:0": { artId: "beach-vibes" },
  "launchpad-collection:1": { artId: "towelie-window" },
  "launchpad-collection:2": { artId: "dance-night" },
  "launchpad-owner:0": { artId: "rose-ape" },
  "launchpad-section:0": { artId: "naka01", objectPosition: "50% 54%" },
  "launchpad-section:1": { artId: "naka02", objectPosition: "50% 50%" },
  "launchpad-section:2": { artId: "naka03", objectPosition: "50% 30%" },
  "launchpad-shared:0": { artId: "rose-ape" },
  "launchpad-shared:1": { artId: "dance-night" },
  "launchpad-traits:0": { artId: "chaos-scene" },
  "launchpad-wizard:0": { artId: "chaos-scene" },
  "leaderboard:0": { artId: "iph_0154" },
  "leaderboard:1": { artId: "ape-hug", objectPosition: "50% 24%" },
  "leaderboard:2": { artId: "beach-vibes", objectPosition: "50% 23%" },
  "leaderboard:3": { artId: "bobowelie", objectPosition: "50% 45%" },
  "leaderboard:4": { artId: "iph_0168" },
  "leaderboard:5": { artId: "splash10", objectPosition: "50% 34%" },
  "lending-section:0": { artId: "rose-ape", objectPosition: "50% 16%" },
  "lending-section:1": { artId: "sword-of-love", objectPosition: "50% 56%" },
  "lending-section:10": { artId: "smoking-duo", objectPosition: "50% 59%" },
  "lending-section:11": { artId: "jb-christmas", objectPosition: "50% 6%" },
  "lending-section:12": { artId: "iph_0181" },
  "lending-section:13": { artId: "porch-chill", objectPosition: "50% 64%" },
  "lending-section:14": { artId: "rose-ape", objectPosition: "50% 39%" },
  "lending-section:2": { artId: "iph_0155" },
  "lending-section:3": { artId: "iph_1061" },
  "lending-section:4": { artId: "naka10", objectPosition: "50% 77%" },
  "lending-section:5": { artId: "iph_0178" },
  "lending-section:6": { artId: "wrestler", objectPosition: "50% 0%" },
  "lending-section:7": { artId: "iph_0173", objectPosition: "50% 69%" },
  "lending-section:8": { artId: "beach-vibes", objectPosition: "50% 42%" },
  "lending-section:9": { artId: "iph_0179", objectPosition: "50% 50%" },
  "liquidity-tab:0": { artId: "iph_0147" },
  "liquidity-tab:1": { artId: "iph_0150" },
  "lp-farming:0": { artId: "iph_1056" },
  "lp-farming:1": { artId: "naka31", objectPosition: "50% 22%" },
  "nft-finance:0": { artId: "naka02", objectPosition: "50% 21%" },
  "nft-finance:1": { artId: "iph_0169" },
  "nft-finance:2": { artId: "naka13", objectPosition: "50% 12%" },
  "nft-finance:3": { artId: "naka16", objectPosition: "50% 69%" },
  "nft-lending:0": { artId: "sword-of-love", objectPosition: "50% 56%" },
  "nft-lending:1": { artId: "iph_0180" },
  "nft-lending:2": { artId: "wrestler", objectPosition: "50% 0%" },
  "nft-lending:3": { artId: "iph_1057" },
  "nft-lending:4": { artId: "iph_0159", objectPosition: "50% 85%" },
  "onboarding:0": { artId: "card01" },
  "onboarding:1": { artId: "card02" },
  "onboarding:2": { artId: "card03" },
  "onboarding:3": { artId: "card04" },
  "premium:0": { artId: "naka12", objectPosition: "50% 54%" },
  "premium:1": { artId: "iph_0177" },
  "privacy:0": { artId: "iph_0171", objectPosition: "50% 89%" },
  "referral-widget:0": { artId: "towelie-window", objectPosition: "50% 43%" },
  "risks:0": { artId: "naka03", objectPosition: "50% 35%" },
  "security:0": { artId: "jbac-skeleton", objectPosition: "50% 38%" },
  "security:1": { artId: "watercolor", objectPosition: "50% 62%" },
  "security:12": { artId: "naka05", objectPosition: "50% 75%" },
  "security:13": { artId: "iph_0160" },
  "security:14": { artId: "iph_0165" },
  "security:15": { artId: "iph_0130" },
  "security:16": { artId: "iph_0146" },
  "security:17": { artId: "naka10", objectPosition: "50% 76%" },
  "security:18": { artId: "iph_0172" },
  "security:19": { artId: "naka12", objectPosition: "50% 75%" },
  "security:2": { artId: "iph_0152" },
  "security:20": { artId: "naka13", objectPosition: "50% 47%" },
  "security:21": { artId: "naka14", objectPosition: "50% 54%" },
  "security:3": { artId: "mumu-bull", objectPosition: "50% 67%" },
  "security:4": { artId: "iph_1058" },
  "security:5": { artId: "naka16", objectPosition: "50% 53%" },
  "security:6": { artId: "splash10", objectPosition: "50% 48%" },
  "security:7": { artId: "iph_1060" },
  "security:8": { artId: "naka01", objectPosition: "50% 59%" },
  "security:9": { artId: "naka02", objectPosition: "50% 53%" },
  "staking-card:0": { artId: "naka14", objectPosition: "50% 30%" },
  "tegridy-score:0": { artId: "iph_0149" },
  "terms:0": { artId: "naka28", objectPosition: "50% 91%" },
  "token-select:0": { artId: "card08" },
  "tokenomics:0": { artId: "iph_0131" },
  "tokenomics:1": { artId: "iph_1066" },
  "tokenomics:2": { artId: "iph_1064" },
  "tokenomics:3": { artId: "splash08", objectPosition: "50% 23%" },
  "tokenomics:4": { artId: "naka22", objectPosition: "50% 6%" },
  "tokenomics:5": { artId: "splash13", objectPosition: "50% 40%" },
  "tokenomics:6": { artId: "naka05" },
  "tokenomics:7": { artId: "iph_0135" },
  "tokenomics:8": { artId: "iph_1067" },
  "trade:0": { artId: "naka01", objectPosition: "50% 7%" },
  "trade:1": { artId: "iph_1062" },
  "trade:2": { artId: "iph_0170", objectPosition: "50% 10%" },
  "trade:3": { artId: "iph_0167", objectPosition: "50% 24%" },
  "tx-receipt:0": { artId: "card06" },
  "typed-confirm:0": { artId: "card07" },
  "upcoming-pools:0": { artId: "iph_0166" },
  "upcoming-pools:1": { artId: "iph_0140" },
  "vote-incentives:0": { artId: "naka28", objectPosition: "50% 58%" },
  "vote-incentives:1": { artId: "naka29", objectPosition: "50% 79%" },
  "vote-incentives:2": { artId: "naka30", objectPosition: "50% 12%" },
  "vote-incentives:3": { artId: "iph_0139", objectPosition: "50% 18%" },
};
