import DERIVATIVES from './artDerivatives.generated.json';

/**
 * The runtime half of the responsive-art pipeline. Its partner is
 * scripts/generate-image-derivatives.mjs, which writes both the derivative files
 * and the manifest this reads.
 *
 * THE CONTRACT BETWEEN THE TWO HALVES, because getting it wrong is silent:
 *   - the generator emits `/_derived/<path-without-ext>-<width>.webp`
 *   - it emits a width only when the source is genuinely WIDER than it
 *   - it records the source's natural width in the manifest, and nothing else
 * `derivedUrl` and `widthsFor` below re-derive exactly those rules.
 * artSrcSet.test.ts pins them against the generator's own source so the two
 * cannot drift apart — a drift here does not throw, it 404s a srcset candidate,
 * and a 404 in a srcset is a broken image rather than a graceful fallback.
 *
 * WHY THIS IS SAFE WHEN THE MANIFEST IS EMPTY. A checkout that has not run the
 * build (a dev server, a fresh clone, CI before `prebuild`) sees `{}`, every
 * lookup misses, and `artSrcSet` returns undefined — so <img> renders exactly as
 * it did before this existed. The failure mode is "no optimisation", never
 * "broken image", which is the same reason the manifest exists at all instead of
 * deriving URLs by convention and hoping they resolve.
 */

/** Kept in lock-step with WIDTHS in scripts/generate-image-derivatives.mjs. */
export const DERIVATIVE_WIDTHS = [480, 960] as const;

const MANIFEST = DERIVATIVES as Record<string, number>;

/** `/art/x.jpg` @480 -> `/_derived/art/x-480.webp`. Mirrors the generator. */
export function derivedUrl(src: string, width: number): string {
  const dot = src.lastIndexOf('.');
  const stem = dot === -1 ? src : src.slice(0, dot);
  return `/_derived${stem}-${width}.webp`;
}

/** The widths that actually exist for this source — never wider than the original. */
export function widthsFor(src: string): number[] {
  const natural = MANIFEST[src];
  if (!natural) return [];
  return DERIVATIVE_WIDTHS.filter((w) => natural > w);
}

/**
 * The `srcset` for an art URL, or `undefined` when there is nothing to offer.
 *
 * The ORIGINAL is always the last candidate, at its true natural width. That is
 * what keeps full-bleed surfaces honest: the same file is rotated through both a
 * 271px thumbnail and a 1280px backdrop by ART_POOL_ALL, so the large candidate
 * has to stay available or the backdrop would be served a 960px upscale.
 */
export function artSrcSet(src: string): string | undefined {
  // PRODUCTION ONLY, and this is the load-bearing safety rail.
  //
  // The manifest is COMMITTED (tsc and vitest need it in a fresh clone) but the
  // 56 MB of derivatives it describes are NOT — they are generated by `prebuild`.
  // So in a dev server that has never run a build, the manifest lists candidates
  // whose files are absent, and a 404 in a srcset is a broken image, not a
  // graceful fallback. In a production build `prebuild` has run by construction:
  // npm runs it before `build`, and `build` is the only way dist/ exists.
  if (!import.meta.env.PROD) return undefined;

  const natural = MANIFEST[src];
  if (!natural) return undefined;
  const widths = widthsFor(src);
  if (widths.length === 0) return undefined;
  return [
    ...widths.map((w) => `${derivedUrl(src, w)} ${w}w`),
    `${src} ${natural}w`,
  ].join(', ');
}

/**
 * The `sizes` hint. `srcset` with `w` descriptors is INERT without one, and the
 * value is what decides whether any of this saves a single byte.
 *
 * THE FIRST ATTEMPT HERE WAS '100vw' AND IT SAVED NOTHING. Measured: images at
 * boot were 5,117,404 B before the change and 5,117,404 B after — byte for byte
 * identical. '100vw' tells the browser the image occupies the full viewport, so
 * for a 271px thumbnail on a 1280px page it dutifully picks the 2048px original.
 * The reasoning behind it ("an over-wide sizes only costs a slightly larger
 * candidate") was simply wrong: over-wide costs you the WHOLE optimisation.
 *
 * `auto` is the fix and is purpose-built for this: the browser uses the element's
 * actual laid-out width, which is the one thing ArtImg genuinely cannot know at
 * render time while backing surfaces from 26px icons to full-bleed heroes. It is
 * only valid on a lazy-loaded image, which is ArtImg's default for everything
 * except the LCP hero — and for that hero '100vw' is not a guess, it is true.
 *
 * A browser without `sizes=auto` support ignores the value and falls back to the
 * 100vw default, i.e. exactly the pre-change behaviour: the original is served,
 * nothing breaks, nobody sees a soft image.
 */
export function artSizes(loading: string | undefined): string {
  return loading === 'lazy' ? 'auto' : '100vw';
}
